### ISSUE TITLE
Error convert SUN raster graphic

### ISSUE THREAD

**Issue by th-otto** [mikrosk/uconvert#2]
The attached file is displayed without problem using the "display" tool from ImageMagick, but uconvert complains with

```Magick: Unexpected end-of-file (abydos_8.sun) reported by coders/sun.c:612 (ReadSUNImage)```

when trying to convert it. Any idea what is going wrong?
The file was taken from https://sembiance.com/fileFormatSamples/image/sunRaster/abydos.im8

[abydos_8.zip](https://github.com/user-attachments/files/18082547/abydos_8.zip)

PS.: did you know that RECOIL supports your format? ;)

**Comment by mikrosk** [comment]
Yeah, a bug in GraphicsMagick:
```
[mikro@pc ~]$ gm display ./abydos_8.sun 
gm display: Unexpected end-of-file (./abydos_8.sun).
```
Which is quite interesting since Bob (the GM maintainer) basically contributes to both projects.

> did you know that RECOIL supports your format?

IIRC that's thanks to @lpgb whom I still owe that VDI palette (which is indeed a natural extension of the format).
