### ISSUE TITLE
ushow uses incorrect colors on Falcon for images stored with STE palette

### ISSUE THREAD

**Issue by th-otto** [mikrosk/uconvert#3]
Only tested on Hatari, so i hope it is not on issue with its videl emulation, but when displaying an image with STE palette, ushow only writes to the STE palette registers. IIRC, that does not change the VIDEL palette, causing such images to use wrong colors.

Similarly, there is IMHO also an issue when displaying images with Falcon palettes. ushow writes to the VIDEL palette in this case, without checking whether actually running on a falcon. That will cause bus-errors on STE/TT.

Edit: ok, there is no bus-error, instead it refuses to display such images. It would be nice if it could just convert the palette.

Edit2: latest zview snapshot now has plugin for your format ;)

**Comment by mikrosk** [comment]
Even if it may sound weird, this is not a bug but a feature: my initial motivation for ushow was to have a tool which shows _exactly_ what is written in the bitmap. So zero conversions behind the scenes and zero help from the tool when writing to hardware.

So in this case yes, you are not supposed to display Falcon pictures on STE and vice versa, STE pictures on Falcon are supposed to be working only when started from ST Low. The real "fix" is to always convert to machine which are you aiming for.
